/**
 * build.js — builds CJS (minified), ESM, and minified CSS into dist/
 *
 * Outputs:
 *   dist/inspector.min.js       — minified CJS  (UMD)  → npm "main"
 *   dist/inspector.esm.js       — ESM wrapper          → npm "module"
 *   dist/inspector.min.css      — minified CSS
 *   dist/inspector.min.js.map   — source map
 *
 * Run:  node scripts/build.js
 * Auto: npm run build / prepublishOnly
 */

const { minify } = require('terser');
const fs         = require('fs');
const path       = require('path');

const DIST    = path.resolve(__dirname, '../dist');
const SRC_JS  = path.join(DIST, 'inspector.js');
const SRC_CSS = path.join(DIST, 'inspector.css');

// ── CJS minified (UMD, same as before) ───────────────────────────────────────
async function buildCJS() {
  const src    = fs.readFileSync(SRC_JS, 'utf8');
  const result = await minify(src, {
    compress: { passes: 2 },
    mangle:   true,
    format:   { comments: false },
    sourceMap: {
      url:      'inspector.min.js.map',
      filename: 'inspector.min.js',
    },
  });
  const out = path.join(DIST, 'inspector.min.js');
  fs.writeFileSync(out, result.code, 'utf8');
  if (result.map) fs.writeFileSync(out + '.map', result.map, 'utf8');
  log('CJS', SRC_JS, out);
}

// ── ESM wrapper ───────────────────────────────────────────────────────────────
// Extracts the inner factory from the UMD IIFE, wraps it as a true ES module.
// UMD shape: ;(function(global,factory){...}(typeof globalThis..., function(){BODY}));
async function buildESM() {
  const src = fs.readFileSync(SRC_JS, 'utf8');

  // Find the last occurrence of the factory body:
  // everything between the opening "function () {" of the factory and the closing "}));"
  const marker = ", function () {\n";
  const start  = src.indexOf(marker);
  const end    = src.lastIndexOf("\n}));");
  const body   = (start !== -1 && end !== -1) ? src.slice(start + marker.length, end) : null;

  if (!body) {
    // Fallback: execute the bundle as-is, then re-export the global it sets
    const esmFallback = [
      '// ESM wrapper — generated by scripts/build.js',
      src,
      'const _insp = (typeof globalThis !== "undefined" ? globalThis : self).DOMInspector;',
      'export default _insp;',
      'export const { init, enable, disable, destroy, on, off, generateStableSelector,',
      '  setTheme, patchAddEventListener, clearMutations, detectFramework,',
      '  audit, connect, disconnect, share, joinSession } = _insp;',
    ].join('\n');
    const out = path.join(DIST, 'inspector.esm.js');
    fs.writeFileSync(out, esmFallback, 'utf8');
    log('ESM', SRC_JS, out);
    return;
  }

  const esmSrc = [
    '// @armvs/dom-inspector — ESM build (generated by scripts/build.js)',
    '// Do not edit — edit dist/inspector.js instead',
    '',
    'const _factory = (function () {',
    "  'use strict';",
    body,
    '});',
    '',
    'const DOMInspector = _factory();',
    '',
    'export default DOMInspector;',
    'export const {',
    '  init, enable, disable, destroy, on, off,',
    '  export: exportData,',
    '  generateStableSelector, setTheme, patchAddEventListener, clearMutations,',
    '  detectFramework, audit, connect, disconnect, share, joinSession,',
    '} = DOMInspector;',
  ].join('\n');

  const result = await minify(esmSrc, {
    compress: { passes: 2 },
    mangle:   true,
    format:   { comments: false },
    module:   true,
  });
  const out = path.join(DIST, 'inspector.esm.js');
  fs.writeFileSync(out, result.code, 'utf8');
  log('ESM', SRC_JS, out);
}

// ── CSS minified ──────────────────────────────────────────────────────────────
function buildCSS() {
  let css = fs.readFileSync(SRC_CSS, 'utf8');
  css = css
    .replace(/\/\*[\s\S]*?\*\//g, '')          // strip comments
    .replace(/\s*([{}:;,>~+])\s*/g, '$1')      // collapse around tokens
    .replace(/\s{2,}/g, ' ')                   // collapse spaces
    .replace(/;\}/g, '}')                      // trailing semicolon before }
    .trim();
  const out = path.join(DIST, 'inspector.min.css');
  fs.writeFileSync(out, css, 'utf8');
  log('CSS', SRC_CSS, out);
}

// ── Helpers ───────────────────────────────────────────────────────────────────
function log(label, src, out) {
  const before = fs.statSync(src).size;
  const after  = fs.statSync(out).size;
  const pct    = Math.round((1 - after / before) * 100);
  console.log(`${label.padEnd(4)} ${kb(before)} → ${kb(after)}  (-${pct}%)`);
}
const kb = (n) => (n / 1024).toFixed(1).padStart(6) + ' KB';

// ── Extension assets ─────────────────────────────────────────────────────────
// Copies minified JS + CSS into extension/ so chrome.runtime.getURL() finds them.
function copyExtensionAssets() {
  const EXT = path.resolve(__dirname, '../extension');
  if (!fs.existsSync(EXT)) return;
  fs.copyFileSync(path.join(DIST, 'inspector.min.js'),  path.join(EXT, 'inspector.js'));
  fs.copyFileSync(path.join(DIST, 'inspector.min.css'), path.join(EXT, 'inspector.css'));
  console.log('EXT  copied inspector.{js,css} → extension/');
}

// ── Main ──────────────────────────────────────────────────────────────────────
(async () => {
  console.log('Building @armvs/dom-inspector…');
  await buildCJS();
  await buildESM();
  buildCSS();
  copyExtensionAssets();
  console.log('Done.');
})().catch(e => { console.error(e); process.exit(1); });
