/**
 * scripts/build.cjs — @armvs/dom-inspector build orchestrator
 *
 * Steps:
 *  1. Generate src/index.js (proper ES Module) from dist/inspector.js (UMD source)
 *  2. Run Rollup (rollup.config.mjs) → produces all JS bundles + source maps
 *  3. Minify dist/inspector.css → dist/inspector.min.css
 *  4. Copy assets into extension/
 */

const { execSync } = require("child_process");
const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const DIST = path.join(ROOT, "dist");
const SRC = path.join(ROOT, "src");

// ── Step 1: Generate src/index.js ────────────────────────────────────────────
function generateESMSource() {
    const srcFile = path.join(DIST, "inspector.js");
    if (!fs.existsSync(srcFile))
        throw new Error(`Source not found: ${srcFile}`);

    // Normalize to LF for reliable string matching
    const src = fs.readFileSync(srcFile, "utf8").replace(/\r\n/g, "\n");

    const factoryMarker = "this, function () {\n  'use strict';\n\n";
    const factoryStart = src.indexOf(factoryMarker);
    if (factoryStart === -1)
        throw new Error("Could not locate UMD factory in dist/inspector.js");

    const bodyStart = factoryStart + factoryMarker.length;
    const bodyEnd = src.lastIndexOf("\n}));");
    if (bodyEnd === -1)
        throw new Error(
            "Could not locate })); end marker in dist/inspector.js",
        );

    const body = src.slice(bodyStart, bodyEnd);
    const returnIdx = body.lastIndexOf("\n  return {");
    if (returnIdx === -1)
        throw new Error("Could not locate return { in factory body");

    const preReturn = body.slice(0, returnIdx);
    const pkg = JSON.parse(
        fs.readFileSync(path.join(ROOT, "package.json"), "utf8"),
    );

    const esmCode = [
        `/**`,
        ` * @armvs/dom-inspector v${pkg.version} — ES Module source`,
        ` * Auto-generated by scripts/build.cjs from dist/inspector.js`,
        ` * Do NOT edit directly — edit dist/inspector.js, then run: npm run build`,
        ` */`,
        ``,
        `/* eslint-disable */`,
        `// @ts-nocheck`,
        ``,
        preReturn,
        ``,
        `  const DOMInspector = {`,
        `    init, enable, disable, destroy,`,
        `    on, off,`,
        `    export: exportData,`,
        `    generateStableSelector,`,
        `    setTheme,`,
        `    patchAddEventListener,`,
        `    clearMutations,`,
        `    detectFramework,`,
        `    audit,`,
        `    connect,`,
        `    disconnect,`,
        `    share,`,
        `    joinSession,`,
        `  };`,
        ``,
        `export default DOMInspector;`,
        `export {`,
        `  init, enable, disable, destroy,`,
        `  on, off,`,
        `  generateStableSelector,`,
        `  setTheme,`,
        `  patchAddEventListener,`,
        `  clearMutations,`,
        `  detectFramework,`,
        `  audit,`,
        `  connect,`,
        `  disconnect,`,
        `  share,`,
        `  joinSession,`,
        `};`,
        `export { exportData as export };`,
        ``,
    ].join("\n");

    if (!fs.existsSync(SRC)) fs.mkdirSync(SRC, { recursive: true });
    fs.writeFileSync(path.join(SRC, "index.js"), esmCode, "utf8");
    console.log(
        `✓ src/index.js       generated  (${(esmCode.length / 1024).toFixed(1)} KB)`,
    );
}

// ── Step 2: Run Rollup ────────────────────────────────────────────────────────
function runRollup() {
    console.log("\nRunning Rollup…");
    // Use npx so Windows CMD resolves the binary correctly (avoids node_modules/.bin path issue)
    execSync("npx rollup -c rollup.config.mjs", {
        cwd: ROOT,
        stdio: "inherit",
    });

    const files = [
        "inspector.mjs",
        "inspector.cjs",
        "inspector.umd.js",
        "inspector.min.js",
    ];
    console.log("");
    for (const f of files) {
        const fp = path.join(DIST, f);
        const size = fs.statSync(fp).size;
        const map = fs.existsSync(fp + ".map") ? "+ map" : "     ";
        console.log(
            `  ${f.padEnd(24)} ${map}  ${(size / 1024).toFixed(1).padStart(7)} KB`,
        );
    }
}

// ── Step 3: Minify CSS ───────────────────────────────────────────────────────
function buildCSS() {
    const srcCss = path.join(DIST, "inspector.css");
    if (!fs.existsSync(srcCss)) {
        console.warn("⚠ inspector.css not found — skipping");
        return;
    }

    let css = fs.readFileSync(srcCss, "utf8");
    css = css
        .replace(/\/\*[\s\S]*?\*\//g, "")
        .replace(/\s*([{}:;,>~+])\s*/g, "$1")
        .replace(/\s{2,}/g, " ")
        .replace(/;}/g, "}")
        .trim();

    const outCss = path.join(DIST, "inspector.min.css");
    fs.writeFileSync(outCss, css, "utf8");
    const before = fs.statSync(srcCss).size;
    const after = fs.statSync(outCss).size;
    const pct = Math.round((1 - after / before) * 100);
    console.log(
        `\n✓ inspector.css → inspector.min.css   ${(before / 1024).toFixed(1)} KB → ${(after / 1024).toFixed(1)} KB  (-${pct}%)`,
    );
}

// ── Step 4: Copy extension assets ────────────────────────────────────────────
function copyExtension() {
    const EXT = path.join(ROOT, "extension");
    if (!fs.existsSync(EXT)) return;
    fs.copyFileSync(
        path.join(DIST, "inspector.min.js"),
        path.join(EXT, "inspector.js"),
    );
    fs.copyFileSync(
        path.join(DIST, "inspector.min.css"),
        path.join(EXT, "inspector.css"),
    );
    console.log("✓ extension/         assets copied");
}

// ── Main ─────────────────────────────────────────────────────────────────────
(async () => {
    console.log("Building @armvs/dom-inspector…\n");
    try {
        generateESMSource();
        runRollup();
        buildCSS();
        copyExtension();
        console.log("\n✅ Build complete.\n");
    } catch (e) {
        console.error("\n❌ Build failed:", e.message);
        process.exit(1);
    }
})();
